services:
  db:
    image: postgres:15-alpine
    container_name: lobby-postgres
    restart: always
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_URL}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: lobby-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data: